**ACTIVIDAD 2.1(EXTRACCION DE DATOS)**
**Detalle precios y productos fabricados 2022.xlsx**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#Carga desde un archivo .xlsx sin indice
df = pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [5]:
#Verificamos informacion del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

**FILTROS BÁSICOS PARA VARIABLES CUALITATIVAS**

**filtros básicos para variables cualitativas**

In [ ]:
#Filtro por Objeto
#Se filtró la columna NOMBRE_CLIENTE con valor PUBLICO EN GENERAL

filtro1= df[(df["NOMBRE_CLIENTE"] == "PÚBLICO EN GENERAL")]
filtro1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
57,F37134,2022-01-17,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,4,RB00010,BOB 8020 CAL.19 1612W 127V CER-8CANALES,605.00,44.70,44.70,2420.00,178.80,560.30,2241.20
69,F37153,2022-01-20,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00245,BAN P COMUN 100CMX21MM 900W220V T/TOR,522.00,51.38,51.38,1044.00,102.76,470.62,941.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1371,F39748,2022-12-09,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,TUE00206,"TUB INOX 5/16""Øx930mm 1000W 127V CAPUCHO",576.65,0.00,366.62,1153.30,733.23,210.03,420.07
1375,F39752,2022-12-13,AARON NUÑO CORDOVA,PÚBLICO EN GENERAL,1,TU5/16X870J127V,"TUB INOX 5/16""ØX800MM 2000W127V ""J"" TBOY",689.63,227.18,227.18,689.63,227.18,462.44,462.44
1376,F39754,2022-12-13,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,4,CS14D2017B20,"CAS INOX 1/4""ØX2"" 175W240V EXT30CM C/TJ",3416.00,222.14,222.14,6832.00,444.27,3193.86,6387.73
1392,F39780,2022-12-16,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TP0012,"TERMOPAR CERAMICO T/ K"" LONG 12"" CAL.14""",410.00,57.60,57.60,410.00,57.60,352.40,352.40
1410,F39817,2022-12-22,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,TP0016,"TERMOPAR CERAMICO T/K"" LONG 24"" CAL 8""",732.00,0.00,317.50,1464.00,635.00,414.50,829.00

In [7]:
#Convertir el archivo filtrado a CSV
filtro1.to_csv("filtrado1(por objeto).csv")

In [ ]:
#Filtro por filas
#Se filtro filas del rango de 3 a 7, y se seleccionó unicamente la fila 2 y 5
filtro= df.iloc[3:7, :]
filtro2= df.iloc[[2,5], :]
filtro2

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32

In [10]:

#Convertir el archivo filtrado a CSV
filtro2.to_csv("filtrado2(por filas).csv")

In [17]:
#Filtro por columnas
#se selecionó las columnas FECHA_DOC Y NOMBRE_VENDEDOR con todas sus filas
filtro3=df.iloc[:, 1:3]
filtro4=df.iloc[:, [1,4,5]]
filtro3

      FECHA_DOC            NOMBRE_VENDEDOR
0    2022-01-05  LETICIA RAMIREZ HERNANDEZ
1    2022-01-05  LETICIA RAMIREZ HERNANDEZ
2    2022-01-05   DIEGO ARMANDO LEON DURAN
3    2022-01-05   DIEGO ARMANDO LEON DURAN
4    2022-01-05  LETICIA RAMIREZ HERNANDEZ
...         ...                        ...
1421 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1422 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1423 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1424 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1425 2022-12-23         AARON NUÑO CORDOVA

[1426 rows x 2 columns]

In [18]:
#Convertir el archivo filtrado a CSV
filtro3.to_csv("filtro3(por columnas).csv")

In [21]:
#Se filtro la columna 2 el cual empieza como columna 1
df1= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx', index_col=2)
df1

,CVE_DOC,FECHA_DOC,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
NOMBRE_VENDEDOR,,,,,,,,,,,,,
LETICIA RAMIREZ HERNANDEZ,F37034,2022-01-05,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
LETICIA RAMIREZ HERNANDEZ,F37036,2022-01-05,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
DIEGO ARMANDO LEON DURAN,F37041,2022-01-05,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
DIEGO ARMANDO LEON DURAN,F37042,2022-01-05,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
LETICIA RAMIREZ HERNANDEZ,F37043,2022-01-05,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
LETICIA RAMIREZ HERNANDEZ,F39834,2022-12-23,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
LETICIA RAMIREZ HERNANDEZ,F39834,2022-12-23,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
LETICIA RAMIREZ HERNANDEZ,F39835,2022-12-23,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
LETICIA RAMIREZ HERNANDEZ,F39837,2022-12-23,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
AARON NUÑO CORDOVA,F39838,2022-12-23,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [22]:
#Convertir el archivo filtrado a CSV
df1.to_csv("Cambio de indice de columna.csv")

In [23]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
#Se selecciona las filas unicamente de AARON NUÑO con la columna CANTIDAD
filtro4= df1.loc[["AARON NUÑO CORDOVA"],["CANT"]]
filtro4

                    CANT
NOMBRE_VENDEDOR
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA     8
AARON NUÑO CORDOVA    20
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA     2
...                  ...
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA    10

[72 rows x 1 columns]

In [25]:
#Convertir el archivo filtrado a CSV
filtro4.to_csv("filtro4 (filas VS columnas).csv")

In [26]:
#Filtro por cabecera
#filtra las primeras 5 filas del DataFrame
filtro5 = df.head()
filtro5

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

In [27]:
#Convertir el archivo filtrado a CSV
filtro5.to_csv("filtro5(por cabecera).csv")

In [28]:
#Filtro por cola
filtro6= df.tail()
filtro6

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [29]:
#Convertir el archivo filtrado a CSV
filtro6.to_csv("filtro6(por cola).csv")

In [32]:
#Filtro por comparacion
#Selecciona solo las filas donde el valor en la columna "MARGEN_TOTAL_CALCULADO" es mayor a 10,000.
filtro7 = df[df["MARGEN_TOTAL_CALCULADO"] > 10000 ]
filtro7

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
29,F37078,2022-01-07,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.60,9163.18,993.88,29816.42
31,F37086,2022-01-10,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.60,9163.18,993.88,29816.42
40,F37102,2022-01-12,ALFREDO CANELA,DEACERO,3,TUE00321,"TUB INOX 1/2""ØX1030MMX980MM 3KW480V ""L""",12720.00,0.00,1509.14,38160.00,4527.42,11210.86,33632.58
65,F37147,2022-01-19,ALFREDO CANELA,VALEO KAPEC,8,TUA00258,"TUB INOX 7/16""Øx190mm 2000W 400V BUS/LAT",2177.50,272.65,272.65,17420.00,2181.22,1904.85,15238.78
74,F37169,2022-01-21,ALFREDO CANELA,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,30,ECQ-00972,"TUB. ENCAPSULADA 5/16Øx780mm 1500W 240V""",1475.30,275.50,275.50,44259.00,8264.95,1199.80,35994.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,F39791,2022-12-20,LETICIA RAMIREZ HERNANDEZ,PLENCO DE MEXICO,6,TUA00433,"TUB INOX 1/2""ØX1015MM 5KW 240V ""U"" ALETA",2494.80,0.00,620.47,14968.80,3722.84,1874.33,11245.96
1397,F39794,2022-12-20,AARON NUÑO CORDOVA,TE.MEX AUTOMOTIVE,26,CAS00083,CAS INOX 12.5MMØX125MM 300W 280V EXT1MT,792.11,131.45,131.45,20594.86,3417.80,660.66,17177.06
1403,F39810,2022-12-22,ALFREDO CANELA,DONGA HWASUNG MEXICO,16,CBS00109,"CBS INOX 5/8""ØX66CM 800W 480V EXT30CM",1981.88,0.00,333.62,31710.08,5337.90,1648.26,26372.18
1409,F39816,2022-12-22,ALFREDO CANELA,TOSTADAS FANNY,6,TUA00492,"TUB INOX 1/2""ØX40CM 4000W 220V ""M"" BUSH",2959.68,0.00,1186.76,17758.08,7120.54,1772.92,10637.54
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [33]:
#Convertir el archivo filtrado a CSV
filtro7.to_csv("filtro7(por comparacion).csv")

In [36]:
#Filtro Y
# Evalúa la columna "NOMBRE_CLIENTE",retorna True para las filas donde el cliente sea exactamente "MOLINERA DE MEXICO".
# y también evalúa la columna "FECHA_DOC",Retorna True para las filas donde la fecha sea exactamente "2022-01-05".
filtro8= df[(df["NOMBRE_CLIENTE"] ==  "MOLINERA DE MEXICO" )& (df["FECHA_DOC"] == "2022-01-05")]
filtro8

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
15,F37058,2022-01-05,DIEGO ARMANDO LEON DURAN,MOLINERA DE MEXICO,5,PT00070,"PT-100 1/8""ØX30MM EXT 1.5MT 3HILOS Z/ESP",192.5,51.73,149.6,481.25,397.08,42.9,84.17

In [37]:
#Convertir el archivo filtrado a CSV
filtro8.to_csv("filtro8(filtro &).csv")

In [39]:
#filtro o
#Se filtra las filas que en la columna NOMBRE_CLIENTE sea MOLINERA DE MEXICO o ELICAMEx
filtro9= df[(df["NOMBRE_CLIENTE"] == "MOLINERA DE MEXICO") | (df["NOMBRE_CLIENTE"] == "ELICAMEX")]
filtro9

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
15,F37058,2022-01-05,DIEGO ARMANDO LEON DURAN,MOLINERA DE MEXICO,5,PT00070,"PT-100 1/8""ØX30MM EXT 1.5MT 3HILOS Z/ESP",192.50,51.73,149.60,481.25,397.08,42.90,84.17
18,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,5,WRE-2133,BAN MICA 120mmØx50mm 850W 440V TTORNILLO,821.30,0.00,78.70,4106.50,393.48,742.60,3713.02
19,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,7,WRE-2774,BAN MICA Ø120MM X 50 MM 700W 440V T TOR,821.30,0.00,75.77,5749.10,530.41,745.53,5218.69
20,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,3,WRE-4885,BAN INOX 36MMØX25MM 150W 240V EXT30CM,496.35,27.43,27.43,1489.05,82.29,468.92,1406.76
286,F37564,2022-03-08,ALFREDO CANELA,ELICAMEX,5,WRE-2137,BAN INOX 170MMØX55MM 1300W 440V C/STD,1103.00,122.14,122.14,5515.00,610.68,980.86,4904.32
687,F38391,2022-06-16,LETICIA RAMIREZ HERNANDEZ,MOLINERA DE MEXICO,12,CBS00098,CBS INOX 8MMØX265MM 500W 220V EXT.1MT,596.60,0.00,120.27,7159.20,1443.18,476.34,5716.02
860,F38698,2022-07-29,ALFREDO CANELA,ELICAMEX,5,WRE-2774,BAN MICA Ø120MM X 50 MM 700W 440V T TOR,821.30,0.00,75.77,4106.50,378.86,745.53,3727.64

In [40]:
#Convertir el archivo filtrado a CSV
filtro9.to_csv("filtro9(filtro o).csv")

In [45]:
#Filtro not
#Se filtra tabla donde la columna NOMBRE_CLIENTE se descarta los datos que el cliente sea PUBLICO EN GENERAL
filtro10=df[~(df["NOMBRE_CLIENTE"] == "PÚBLICO EN GENERAL")]
filtro10

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [46]:
#Convertir el archivo filtrado a CSV
filtro10.to_csv("filtro10(filtro not).csv")